[package]
name = "rbquest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magnus = { version = "0.5.1", features = ["embed"] }
rutie = "0.8.4"
